---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ethereum-pv
  labels:
    pv: ethereum-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/ethereum
    server: 10.250.218.55

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-pvc
  namespace: ethereum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      pv: ethereum-pv
